version: '3'

services:
  # Web application
  web:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mnist
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - model_data:/app/mnist_app/model/saved_model
    networks:
      - mnist-network

  # PostgreSQL database
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mnist
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mnist-network

volumes:
  postgres_data:
  model_data:


networks:
  mnist-network:
    driver: bridge
